version: "3.9"
services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/apps
    ports:
      - 3000:3000
      - 4000:4000
  db:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: