version: "3.9"
services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/apps
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${API_PORT}:${API_PORT}
  db:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: