version: "3.9"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
      - cache

  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/home/web
    ports:
      - ${APP_PORT}:${APP_PORT}

  scraper:
    build:
      context: scraper
      dockerfile: Dockerfile.dev
    volumes:
      - ./scraper:/home/scraper

  db:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - db:/var/lib/postgresql/data/

  cache:
    image: redis:7.0.0-alpine3.15
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - cache:/data

volumes:
  db:
  cache: