FROM python:3.10.4-buster
WORKDIR /home/scraper/src

# Install some required packages
RUN apt-get update
RUN apt-get -y install curl git

# Install Node.js and Nodemon
RUN curl -sL https://deb.nodesource.com/setup_17.x  | bash -
RUN apt-get -y install nodejs
RUN npm install --global nodemon

# Install Python dependencies
RUN pip install psycopg2 beautifulsoup4 requests

# Run the scraper
CMD ["nodemon", "--exec", "python3", "main.py"]
